#!/bin/bash
# Final check commands for Bioconductor submission
# Run these commands in your R environment

echo "=== Final Checks for Bioconductor Submission ==="
echo ""
echo "1. Install required packages:"
echo "   install.packages(c('BiocManager', 'roxygen2', 'devtools'))"
echo "   BiocManager::install('BiocCheck')"
echo ""
echo "2. Set working directory to package root:"
echo "   setwd('/path/to/mirDIP-R')"
echo ""
echo "3. Run the following R commands:"
echo ""
echo "   # Generate documentation"
echo "   roxygen2::roxygenise()"
echo ""
echo "   # Run R CMD check"
echo "   devtools::check()"
echo ""
echo "   # Run BiocCheck"
echo "   BiocCheck::BiocCheck('.')"
echo ""
echo "   # Test vignette building"
echo "   devtools::build_vignettes()"
echo ""
echo "   # Run tests"
echo "   devtools::test()"
echo ""
echo "   # Build package"
echo "   devtools::build()"
echo ""
echo "4. Alternative: Run the automated script:"
echo "   source('run_final_checks.R')"
echo ""
echo "=== Expected Results ==="
echo "✓ All checks should pass without errors"
echo "✓ Package tarball (.tar.gz) should be created"
echo "✓ Vignette should build successfully"
echo "✓ All tests should pass"
echo ""
echo "=== Bioconductor Submission ==="
echo "1. Go to: https://github.com/Bioconductor/Contributions"
echo "2. Create new issue: 'New package: mirDIP'"
echo "3. Upload the generated .tar.gz file"
echo "4. Fill out the submission template"
