#!/bin/bash
# Commands to run after renaming the repository on GitHub

echo "=== Repository Rename Commands ==="
echo ""
echo "1. First, rename the repository on GitHub:"
echo "   - Go to: https://github.com/jaimefalcon/mirDIP-R"
echo "   - Click Settings"
echo "   - Change repository name from 'mirDIP-R' to 'mirDIP'"
echo "   - Click Rename"
echo ""
echo "2. Then run these commands:"
echo ""
echo "   # Update remote URL"
echo "   git remote set-url origin git@github.com:jaimefalcon/mirDIP.git"
echo ""
echo "   # Verify the change"
echo "   git remote -v"
echo ""
echo "   # Push to renamed repository"
echo "   git push -u origin main"
echo ""
echo "3. Update any GitHub Actions workflows if needed"
echo ""
echo "=== After renaming, your repository will be at: ==="
echo "https://github.com/jaimefalcon/mirDIP"
