name: pkgdown

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install system deps
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::BiocManager
            local::.
          needs: website
      - name: Install BiocStyle
        run: Rscript -e "if (!requireNamespace('BiocManager', quietly=TRUE)) install.packages('BiocManager'); BiocManager::install('BiocStyle', ask = FALSE, update = FALSE)"
      - name: Build site
        run: Rscript -e 'pkgdown::build_site(preview = FALSE, lazy = TRUE)'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
